#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include<conio.h>
// Global Definition

struct emp
{
    char name[80];          //name of employee
    int emp_id;             //employee id generated by program
    char join_date[12];     //joining date of employee
    char dept[20];
    int sal;                //employee salary
    char password[32];      //age of employee

    struct personalinfo     //personal information
    {

        char address[150];  //address of employee
        char emailid[20];   //Email id of employee
        char ph_no[11];     //employee phone number
        char emerph_no[11]; //employee's emergency phone number

    }pi;                    //Nested structure personal info variable creation

};

void edit_admin();
int admin_pass();

/* Main function started */

int main()
{    system("COLOR 3F");
    //Variables Declarations
    struct emp e;
    int pss,op,op1;
    int recsize;        // size of each record of employee
    int tot_rec;        // it will be used to calculate total no of records in the file

    int c=0;
    FILE *fp=NULL;
    FILE *ft=NULL;      // file pointers

    char another ;
    int choice ;

    char password[32];  // string to store name of the employee used to compare with original before any kind of editing
    int id;             // store id of the employee used to compare with original before any kind of editing

    //FUNCTION DECLARATIONS
    void swap(struct emp* ,struct emp*);    // it is used in sorting functions to swap 2 records

    int checkentry(int,char[32],FILE*);     // it is used to check if id and password are present in list or not

    struct emp read_rec();                  // To read records from user

    void view_rec(struct emp);              // To print record

    void sort_name_asc(FILE *,int );        // To sort name wise in ascending
    void sort_name_desc(FILE *,int );       // To sort name wise in descending

    void sort_sal_asc(FILE *,int );         // To sort salary wise in ascending
    void sort_sal_desc(FILE *,int );        // To sort salary wise in descending

    void sort_jd_asc(FILE *,int );          // To sort Joining Date wise in ascending
    void sort_jd_desc(FILE *,int );         // To sort Joining Date wise in descending


    fp = fopen("EMP.DAT","rb+");

    if(fp == NULL)
    {
        fp = fopen("EMP.DAT","wb+");
        if(fp == NULL)
        {
            printf("Cannot open file");
            exit(1);
        }
    }
    recsize = sizeof(e);
    S1: system("cls");
        printf("\n\n\t\t\t\t\t##################################");
        printf("\n\n\t\t\t\t\t    EMPLOYEE MANAGEMENT SYSTEM");
        printf("\n\n\t\t\t\t\t##################################");
        printf("\n\t\t\t\t\t\t   \xB2  MAIN MENU \xB2\n\n\n\t\t1. ADMINISTRATOR MENU \n\n\t\t2. EMPLOYEE MENU \n\n\t\t3. Exit \n\n\n\t\tEnter Your Choice : ");
    scanf("%d",&choice);

   switch (choice)
    {
    case 2 :
                S3: system("cls");
                    printf("\n\n\t\t\t\t\t\xB2\xB2\xB2\xB2\t  WELCOME TO EMPLOYEES MENU \t\xB2\xB2\xB2\xB2\n\n\n");
                    printf("\n 1. List Records");
                    printf("\n 2. Search Records");
                    printf("\n 3. Sort Records");
                    printf("\n 4. Change password"); // option for changing password of record      // ask password and id before changing
                    printf("\n 5. Exit\n"); // exit from the program
                    printf("\n Your Choice : "); // enter the choice 1,2,3,4,5,6,7,8
                    scanf("%d",&op);
                while (1)
                {
                switch(op)
                {
                case 1://VIEW or LIST
                    system("cls");
                        printf("\n\n\t\t\t\t **********************************");
                        printf("\n\n\t\t\t\t       WELCOME TO VIEW RECORD");
                        printf("\n\n\t\t\t\t **********************************\n\n");

                    rewind(fp); //this moves file cursor to start of the file
                    if(fread(&e,recsize,1,fp)==0)   // If list is empty
                        printf(" No Employees In The Company :(");
                    rewind(fp);
                    while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                    {
                        // printing employee records
                        view_rec(e);        // Function Call
                    }
                    getch();
                    goto S3;

                    break;



                 case 2://SEARCH
                 system("cls");

                        printf("\n\n\t\t\t\t\t **********************************");
                        printf("\n\n\t\t\t\t\t       WELCOME TO SEARCH RECORD");
                        printf("\n\n\t\t\t\t\t **********************************\n\n");
                    tot_rec=0;
                    rewind(fp);
                    while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                    {
                        // printing employee records
                        tot_rec++;
                    }

                    if(tot_rec==0)
                        printf("No Employee In The Company :((");
                    else
                    {
                        another = 'y';
                        while(another == 'y')
                        {
                            fflush(stdin);

                            printf("\n Enter The Employee ID To Search : ");
                            scanf("%d",&id);

                            rewind(fp);
                            c=0;
                            while(fread(&e,recsize,1,fp))  // fetch all record from file
                            {
                                c++;
                                if((e.emp_id==id))  //if id and password matches
                                {
                                    fflush(stdin);
                                    printf("\n Record found . Do you want to see it(y/n)? : ");
                                    another=getchar();
                                    if(another=='y')
                                    {   printf("\n Employee ID           : %d ",e.emp_id);
                                        printf("\n Employee name         : %s ",e.name);
                                        printf("\n Employee Email ID     : %s ",e.pi.emailid);
                                        printf("\n Employee Phone Number : %s ",e.pi.ph_no);
                                        printf("\n Department            : %s ",e.dept);
                                        getch();
                                        goto S3;
                                     }
                                    else if(another=='n')
                                        goto S3;
                                        break;
                                }
                                    /*else
                                        printf("\n Invalid Selection");*/
                            }
                                if(c==tot_rec)
                                    printf("\n No Record Found :(");
                                    getch();



                            printf("\n Search Another Record(y/n)? :");
                            fflush(stdin);
                            another = getchar();
                        }

                    }
                        getch();
                        goto S3;

                    break;




                    case 3://SORT
                 system("cls");

                        printf("\n\n\t\t\t\t\t **********************************");
                        printf("\n\n\t\t\t\t\t       WELCOME TO SORT RECORD");
                        printf("\n\n\t\t\t\t\t **********************************\n\n");
                    tot_rec=0;
                    rewind(fp);
                    while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                    {
                        // printing employee records
                        tot_rec++;
                    }

                    if(tot_rec==0)
                        printf("List is empty -_-");
                    else
                    {
                        printf("\n 1. To Sort the list based on Employee Name\n\n 2. To Sort the list based on Joining Date\n\n Your Choice : ");
                        scanf("%d",&choice);
                        rewind(fp);
                        switch(choice)
                        {
                             case 1 ://sort name wise

                                    printf("\n 1. To Sort the list based on Employee name in Ascending order\n 2. To Sort the list based on Employee name in Descending order \n Your Choice : ");
                                    scanf("%d",&choice);

                                    switch(choice)
                                    {
                                        case 1 ://sort name ascending

                                                sort_name_asc(fp,tot_rec);         //function call

                                                rewind(fp); //this moves file cursor to start of the file

                                                while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                                                {
                                                    // printing employee records

                                                      view_rec(e);
                                                }
                                                getch();
                                                goto S3;

                                                break;
                                        case 2 ://sort name descending
                                                sort_name_desc(fp,tot_rec);        //function call
                                                rewind(fp); //this moves file cursor to start of the file

                                                while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                                                {
                                                    // printing employee records

                                                    view_rec(e);
                                                }

                                                break;

                                        default : printf("\n Invalid Entry");
                                    }
                                    getch();
                                    goto S3;

                                    break;





                            case 2 ://sort joining date wise

                                    printf("\n 1. To Sort the list based on Joining Date in Ascending order\n 2. To Sort the list based on Join Date in Descending order \n Your Choice : ");
                                    scanf("%d",&choice);
                                    switch(choice)
                                    {
                                        case 1 ://sort join date ascending

                                                sort_jd_asc(fp,tot_rec);        //function call
                                                rewind(fp); //this moves file cursor to start of the file

                                                while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                                                {
                                                    // printing employee records

                                                    view_rec(e);
                                                }
                                                getch();
                                                goto S3;              //function call
                                                break;
                                        case 2 ://sort join date descending
                                                sort_jd_desc(fp,tot_rec);        //function call
                                                rewind(fp); //this moves file cursor to start of the file

                                                while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                                                {
                                                    // printing employee records

                                                    view_rec(e);
                                                }

                                                break;
                                        default : printf("invalid entry");
                                    }

                                    break;


                            default : printf("invalid entry");
                        }
                        getch();
                        goto S3;
                    }
                     getch();
                     goto S3;
                    break;

                    case 4://Change Password
                 system("cls");

                        printf("\n\n\t\t\t\t\t ************************************");
                        printf("\n\n\t\t\t\t\t      WELCOME TO CHANGE PASSWORD");
                        printf("\n\n\t\t\t\t\t ************************************\n\n");
                    rewind(fp); //this moves file cursor to start of the file
                    if(fread(&e,recsize,1,fp)==0)   // If list is empty
                        printf(" List is empty");
                    else
                    {
                        another = 'y';
                        while(another == 'y')
                        {

                            printf("\n Enter The Employee ID To Change Password : ");
                            scanf("%d",&id);

                            fflush(stdin);
                            printf("\n To Modify You Need To Enter Old Password: ");
                            scanf("%s",password);
                            rewind(fp);
                            if(checkentry(id,password,fp))
                            {
                                rewind(fp);
                                while(fread(&e,recsize,1,fp))  // fetch all record from file
                                {
                                    if((e.emp_id==id)&&(strcmp(password,e.password)==0))  //if id and password matches
                                    {
                                        fflush(stdin);

                                        printf("\n Enter New Password :- ");
                                        scanf("%s",e.password);
                                        while(1)
                                        {

                                            fflush(stdin);

                                            printf("\n Confirm New Password :- ");
                                            scanf("%s",password);

                                            if(strcmp(e.password,password)==0)

                                                break;
                                            {
                                                printf("\n Enter New Password :- ");
                                                scanf("%s",e.password);
                                            }
                                        }
                                        fseek(fp,-recsize,SEEK_CUR); // move the cursor 1 step back from current position
                                        fwrite(&e,recsize,1,fp); // override the record
                                        printf("\n Your Password is changed Successfully ");


                                        break;
                                    }
                                }
                            }
                            else



                                printf("\n No Record Found");
                                printf("\n Change password of another record (y/n)? :");
                                fflush(stdin);
                                another = getchar();

                        }
                    }

                     getch();
                    goto S3;
                    break;

            case 5:

                //fclose(fp);  // close the file
                goto S1;

            default:printf("\nInvalid Entry -_-\n");
            getch();
                goto S3;
                }
            }


case 1 :
                system("cls");
//                printf("\n\n\n\t\t\tEnter Password : ");
//                scanf("%d",&pss);
                int choice = admin_pass();
                if(!choice)
                {
            S2 :system("cls");
                printf("\n\n\t\t\t\t\t\xB2\xB2\xB2\xB2\tWelcome to Administrator Menu\t\xB2\xB2\xB2\xB2\n\n\n");
                printf("\n\n 1. Change Admin Password");
                printf("\n 2. Add Record"); // option for add record
                printf("\n 3. List Records"); // option for showing existing record
                printf("\n 4. Modify Records"); // option for modifying record      // ask password and id before editing
                printf("\n 5. Delete Records"); // option for deleting record       // ask password and id before deleting
                printf("\n 6. Search Records"); // option for searching record
                printf("\n 7. Sort Records"); // option for sort record             //3 options by name ,join date, salary
                printf("\n 8. Change password"); // option for changing password of record      // ask password and id before changing
                printf("\n 9. Exit\n"); // exit from the program
                printf("\n Your Choice: "); // enter the choice 1,2,3,4,5,6,7,8
                scanf("%d",&op1);
                while(1)
                {
                    switch(op1)
                     {

            case 1 :
                edit_admin();
                goto S2;
                break;

            case 2://ADD RECORD
                 system("cls");

                        printf("\n\n\t\t\t\t\t **********************************");
                        printf("\n\n\t\t\t\t\t       WELCOME TO ADD RECORD");
                        printf("\n\n\t\t\t\t\t **********************************\n\n");

                    fseek(fp,0,SEEK_END); // search the file and move cursor to end of the file
                    // here 0 indicates moving 0 distance from the end of the file

                    another = 'y';
                    while(another == 'y')  // till user want to add another record
                    {
                        e=read_rec();       //Function Call

                        fwrite(&e,recsize,1,fp); // write the record in the file

                        printf("\n Add another record(y/n)? :");  // if user want to add another record

                        fflush(stdin);

                        another = getchar();

                    }
                     getch();
                     goto S2;
                    break;

            case 3://VIEW or LIST
                    system("cls");
                        printf("\n\n\t\t\t\t **********************************");
                        printf("\n\n\t\t\t\t       WELCOME TO VIEW RECORD");
                        printf("\n\n\t\t\t\t **********************************\n\n");

                    rewind(fp); //this moves file cursor to start of the file
                    if(fread(&e,recsize,1,fp)==0)   // If list is empty
                        printf(" No Employees In The Company :(");
                    rewind(fp);
                    while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                    {
                        // printing employee records
                        view_rec(e);        // Function Call
                    }
                    getch();
                    goto S2;

                    break;

            case 4: //MODIFY
                 system("cls");

                        printf("\n\n\t\t\t\t\t **********************************");
                        printf("\n\n\t\t\t\t\t       WELCOME TO MODIFY RECORD");
                        printf("\n\n\t\t\t\t\t **********************************\n\n");
                    rewind(fp); //this moves file cursor to start of the file
                    if(fread(&e,recsize,1,fp)==0)   // If list is empty
                        printf("No Record To Modify -_-");
                    else
                    {
                        another = 'y';
                        while(another == 'y')
                        {
                            printf("\n Enter The Employee ID To Modify : ");
                            scanf("%d",&id);
                            fflush(stdin);
                            printf("\n To Modify You Need To Enter Password : ");
                            scanf("%s",password);
                            rewind(fp);
                            if(checkentry(id,password,fp))
                            {
                                rewind(fp);
                                while(fread(&e,recsize,1,fp))  // fetch all record from file
                                {
                                    if((e.emp_id==id)&&(strcmp(password,e.password)==0))  //if id and password matches
                                    {
                                        e=read_rec();
                                        fseek(fp,-recsize,SEEK_CUR); // move the cursor 1 step back from current position
                                        fwrite(&e,recsize,1,fp); // override the record
                                        printf("\n Modification Successful ");
                                        getch();
                                        goto S2;
                                        break;
                                    }
                                }
                            }
                            else
                                printf("\n No Record Found :(");

                            printf("\n Modify Another Record(y/n)? :");
                            fflush(stdin);
                            another = getchar();
                        }
                    }
                     getch();
                     goto S2;
                    break;

             case 5://DELETE
                  system("cls");

                        printf("\n\n\t\t\t\t\t **********************************");
                        printf("\n\n\t\t\t\t\t       WELCOME TO DELETE RECORD");
                        printf("\n\n\t\t\t\t\t **********************************\n\n");
                    rewind(fp); //this moves file cursor to start of the file
                    if(fread(&e,recsize,1,fp)==0)   // If list is empty
                        printf("No Employee Record To Fire :)");
                    else
                    {
                        another = 'y';
                        while(another == 'y')
                        {
                            printf("\n Enter The Employee ID To Delete : ");
                            scanf("%d",&id);
                            fflush(stdin);
                            printf("\n To Delete You Need To Enter Employee Password : ");
                            scanf("%s",password);

                            ft = fopen("Temp.dat","wb");  // create a intermediate file for temporary storage
                            rewind(fp); // move record to starting of file
                            if(checkentry(id,password,fp))
                            {
                                rewind(fp);
                                while(fread(&e,recsize,1,fp) == 1)  // read all records from file
                                {
                                    if((e.emp_id==id)&&(strcmp(password,e.password)==0))  //if id and password matches
                                        continue;
                                    else
                                        fwrite(&e,recsize,1,ft); // move all records except the one that is to be deleted to temp file
                                }

                                fclose(fp);
                                fclose(ft);

                                remove("EMP.DAT"); // remove the original file
                                rename("Temp.dat","EMP.DAT"); // rename the temp file to original file name

                                fp = fopen("EMP.DAT", "rb+");
                            printf("\n Record Deleted Successfully :)");
                            printf("\n Delete Another Record(y/n)? :");

                            fflush(stdin);

                            another = getchar();
                            }
                            else
                            {
                                printf("\n No Record Found :(");
                                printf("\n Delete Another Record(y/n)? :");
                                fflush(stdin);
                                another = getchar();
                            }
                        }
                    }
                     getch();
                     goto S2;

                    break;

            case 6://SEARCH
                 system("cls");

                        printf("\n\n\t\t\t\t\t **********************************");
                        printf("\n\n\t\t\t\t\t       WELCOME TO SEARCH RECORD");
                        printf("\n\n\t\t\t\t\t **********************************\n\n");
                    tot_rec=0;
                    rewind(fp);
                    while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                    {
                        // printing employee records
                        tot_rec++;
                    }

                    if(tot_rec==0)
                        printf("No Employee In The Company :((");
                    else
                    {
                        another = 'y';
                        while(another == 'y')
                        {
                            fflush(stdin);

                            printf("\n Enter The Employee ID To Search : ");
                            scanf("%d",&id);

                            rewind(fp);
                            c=0;
                            while(fread(&e,recsize,1,fp))  // fetch all record from file
                            {
                                c++;
                                if((e.emp_id==id))  //if id and password matches
                                {
                                    fflush(stdin);
                                    printf("\n Record found . Do you want to see it ?(y/n) ");
                                    another=getchar();
                                    if(another=='y')
                                    {       printf("\n Employee name                      : %s ",e.name);
                                            printf("\n Employee ID                        : %d ",e.emp_id);
                                            printf("\n Employee Joining Date (dd/mm/yyyy) : %s ",e.join_date);
                                            printf("\n Department                         : %s ",e.dept);
                                            printf("\n Employee Salary                    : %d ",e.sal);
                                            printf("\n Employee Address                   : %s ",e.pi.address);
                                            printf("\n Employee Email ID                  : %s ",e.pi.emailid);
                                            printf("\n Employee Phone Number              : %s ",e.pi.ph_no);
                                            printf("\n Employee Emergency Phone Number    : %s ",e.pi.emerph_no);
                                            printf("\n Employee PASSWORD                  : %s\n\n",e.password);
                                        getch();
                                        goto S2;
                                        break;
                                    }
                                    else if(another=='n')
                                        goto S2;
                                        break;
                                }
                                    /*else
                                        printf("\n Invalid Selection");*/
                            }
                                if(c==tot_rec)
                                    printf("\n No Record Found :(");
                                    getch();



                            printf("\n Search Another Record(y/n)? :");
                            fflush(stdin);
                            another = getchar();
                        }

                    }

                     getch();
                     goto S2;

                    break;

            case 7://SORT
                 system("cls");

                        printf("\n\n\t\t\t\t\t **********************************");
                        printf("\n\n\t\t\t\t\t       WELCOME TO SORT RECORD");
                        printf("\n\n\t\t\t\t\t **********************************\n\n");
                    tot_rec=0;
                    rewind(fp);
                    while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                    {
                        // printing employee records
                        tot_rec++;
                    }

                    if(tot_rec==0)
                        printf("List is empty");
                    else
                    {
                        printf("\n 1. To Sort the list based on Employee Name\n 2. To Sort the list based on Salary\n 3. To Sort the list based on Join Date  \n Your Choice : ");
                        scanf("%d",&choice);
                        rewind(fp);
                        switch(choice)
                        {
                            case 1 ://sort name wise

                                    printf("\n 1. To Sort the list based on Employee name in Ascending order\n 2. To Sort the list based on Employee name in Descending order \n Your Choice : ");
                                    scanf("%d",&choice);

                                    switch(choice)
                                    {
                                        case 1 ://sort name ascending

                                                sort_name_asc(fp,tot_rec);         //function call

                                                rewind(fp); //this moves file cursor to start of the file

                                                while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                                                {
                                                    // printing employee records

                                            printf("\n Employee name                      : %s ",e.name);
                                            printf("\n Employee ID                        : %d ",e.emp_id);
                                            printf("\n Employee Joining Date (dd/mm/yyyy) : %s ",e.join_date);
                                            printf("\n Department                         : %s ",e.dept);
                                            printf("\n Employee Salary                    : %d ",e.sal);
                                            printf("\n Employee Address                   : %s ",e.pi.address);
                                            printf("\n Employee Email ID                  : %s ",e.pi.emailid);
                                            printf("\n Employee Phone Number              : %s ",e.pi.ph_no);
                                            printf("\n Employee Emergency Phone Number    : %s ",e.pi.emerph_no);
                                            printf("\n Employee PASSWORD                  : %s\n\n",e.password);
                                                }
                                                getch();
                                                goto S2;

                                                break;
                                        case 2 ://sort name descending
                                                sort_name_desc(fp,tot_rec);        //function call
                                                rewind(fp); //this moves file cursor to start of the file

                                                while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                                                {
                                                    // printing employee records

                                            printf("\n Employee name                      : %s ",e.name);
                                            printf("\n Employee ID                        : %d ",e.emp_id);
                                            printf("\n Employee Joining Date (dd/mm/yyyy) : %s ",e.join_date);
                                            printf("\n Department                         : %s ",e.dept);
                                            printf("\n Employee Salary                    : %d ",e.sal);
                                            printf("\n Employee Address                   : %s ",e.pi.address);
                                            printf("\n Employee Email ID                  : %s ",e.pi.emailid);
                                            printf("\n Employee Phone Number              : %s ",e.pi.ph_no);
                                            printf("\n Employee Emergency Phone Number    : %s ",e.pi.emerph_no);
                                            printf("\n Employee PASSWORD                  : %s\n\n",e.password);
                                                }

                                                break;

                                        default : printf("\n Invalid Entry");
                                    }
                                    getch();
                                    goto S2;

                                    break;

                            case 2 ://sort salary wise

                                    printf("\n 1. To Sort the list based on Salary in Ascending order\n 2. To Sort the list based on Salary in Descending order \n Your Choice : ");
                                    scanf("%d",&choice);
                                    switch(choice)
                                    {
                                        case 1 ://sort salary ascending

                                                sort_sal_asc(fp,tot_rec);        //function call
                                                rewind(fp); //this moves file cursor to start of the file

                                                while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                                                {
                                                    // printing employee records

                                            printf("\n Employee name                      : %s ",e.name);
                                            printf("\n Employee ID                        : %d ",e.emp_id);
                                            printf("\n Employee Joining Date (dd/mm/yyyy) : %s ",e.join_date);
                                            printf("\n Department                         : %s ",e.dept);
                                            printf("\n Employee Salary                    : %d ",e.sal);
                                            printf("\n Employee Address                   : %s ",e.pi.address);
                                            printf("\n Employee Email ID                  : %s ",e.pi.emailid);
                                            printf("\n Employee Phone Number              : %s ",e.pi.ph_no);
                                            printf("\n Employee Emergency Phone Number    : %s ",e.pi.emerph_no);
                                            printf("\n Employee PASSWORD                  : %s\n\n",e.password);
                                                }

                                                break;
                                        case 2 ://sort salary descending
                                                sort_sal_desc(fp,tot_rec);        //function call
                                                rewind(fp); //this moves file cursor to start of the file

                                                while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                                                {
                                                    // printing employee records

                                            printf("\n Employee name                      : %s ",e.name);
                                            printf("\n Employee ID                        : %d ",e.emp_id);
                                            printf("\n Employee Joining Date (dd/mm/yyyy) : %s ",e.join_date);
                                            printf("\n Department                         : %s ",e.dept);
                                            printf("\n Employee Salary                    : %d ",e.sal);
                                            printf("\n Employee Address                   : %s ",e.pi.address);
                                            printf("\n Employee Email ID                  : %s ",e.pi.emailid);
                                            printf("\n Employee Phone Number              : %s ",e.pi.ph_no);
                                            printf("\n Employee Emergency Phone Number    : %s ",e.pi.emerph_no);
                                            printf("\n Employee PASSWORD                  : %s\n\n",e.password);
                                                }

                                                break;
                                        default : printf("invalid Entry");
                                    }
                                    getch();
                                    goto S2;

                                    break;
                            case 3 ://sort joining date wise

                                    printf("\n 1. To Sort the list based on Join Date in Ascending order\n 2. To Sort the list based on Join Date in Descending order \n Your Choice : ");
                                    scanf("%d",&choice);
                                    switch(choice)
                                    {
                                        case 1 ://sort join date ascending

                                                sort_jd_asc(fp,tot_rec);        //function call
                                                rewind(fp); //this moves file cursor to start of the file

                                                while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                                                {
                                                    // printing employee records

                                            printf("\n Employee name                      : %s ",e.name);
                                            printf("\n Employee ID                        : %d ",e.emp_id);
                                            printf("\n Employee Joining Date (dd/mm/yyyy) : %s ",e.join_date);
                                            printf("\n Department                         : %s ",e.dept);
                                            printf("\n Employee Salary                    : %d ",e.sal);
                                            printf("\n Employee Address                   : %s ",e.pi.address);
                                            printf("\n Employee Email ID                  : %s ",e.pi.emailid);
                                            printf("\n Employee Phone Number              : %s ",e.pi.ph_no);
                                            printf("\n Employee Emergency Phone Number    : %s ",e.pi.emerph_no);
                                            printf("\n Employee PASSWORD                  : %s\n\n",e.password);
                                                }
                                                getch();
                                                goto S2;              //function call
                                                break;
                                        case 2 ://sort join date descending
                                                sort_jd_desc(fp,tot_rec);        //function call
                                                rewind(fp); //this moves file cursor to start of the file

                                                while(fread(&e,recsize,1,fp))  // read the file and fetch the record one record per fetch
                                                {
                                                    // printing employee records

                                            printf("\n Employee name                      : %s ",e.name);
                                            printf("\n Employee ID                        : %d ",e.emp_id);
                                            printf("\n Employee Joining Date (dd/mm/yyyy) : %s ",e.join_date);
                                            printf("\n Department                         : %s ",e.dept);
                                            printf("\n Employee Salary                    : %d ",e.sal);
                                            printf("\n Employee Address                   : %s ",e.pi.address);
                                            printf("\n Employee Email ID                  : %s ",e.pi.emailid);
                                            printf("\n Employee Phone Number              : %s ",e.pi.ph_no);
                                            printf("\n Employee Emergency Phone Number    : %s ",e.pi.emerph_no);
                                            printf("\n Employee PASSWORD                  : %s\n\n",e.password);
                                                }

                                                break;
                                        default : printf("invalid entry");
                                    }

                                    break;


                            default : printf("invalid entry");
                        }
                        getch();
                        goto S2;
                    }
                     getch();
                     goto S2;
                    break;


            case 8://Change Password
                     system("cls");
                        printf("\n\n\t\t\t\t\t ************************************");
                        printf("\n\n\t\t\t\t\t      WELCOME TO CHANGE PASSWORD");
                        printf("\n\n\t\t\t\t\t ************************************\n\n");
                    rewind(fp); //this moves file cursor to start of the file
                    if(fread(&e,recsize,1,fp)==0)   // If list is empty
                        printf(" List is empty");
                    else
                    {
                        another = 'y';
                        while(another == 'y')
                        {

                            printf("\n Enter The Employee ID To Change Password : ");
                            scanf("%d",&id);

                            fflush(stdin);
                            printf("\n To Modify You Need To Enter Old Password: ");
                            scanf("%s",password);
                            rewind(fp);
                            if(checkentry(id,password,fp))
                            {
                                rewind(fp);
                                while(fread(&e,recsize,1,fp))  // fetch all record from file
                                {
                                    if((e.emp_id==id)&&(strcmp(password,e.password)==0))  //if id and password matches
                                    {
                                        fflush(stdin);

                                        printf("\n Enter New Password :- ");
                                        scanf("%s",e.password);
                                        while(1)
                                        {

                                            fflush(stdin);

                                            printf("\n Confirm New Password :- ");
                                            scanf("%s",password);

                                            if(strcmp(e.password,password)==0)
                                                break;

                                            {
                                                printf("\n Enter New Password :- ");
                                                scanf("%s",e.password);
                                            }
                                        }
                                        fseek(fp,-recsize,SEEK_CUR); // move the cursor 1 step back from current position
                                        fwrite(&e,recsize,1,fp); // override the record
                                        printf("\n Your Password is changed Successfully ");
                                        break;
                                    }
                                }
                            }
                            else
                                printf("\n No Record Found");
                            printf("\n Change password of another record (y/n)? :");
                            fflush(stdin);
                            another = getchar();
                        }
                    }
                     getch();
                     goto S2;
                     break;


            case 9: //exit
                 goto S1;
               break;

            default: printf("Invalid Entry");
            getch();
             goto S2;

            break;
                }



        }
    }
case 3 :
                printf("\n\n\t\t\t\xB2\xB2\xB2 Thankyou for using this Portal, Please Visit Again \xB2\xB2\xB2\n\n");
                fclose(fp);  // close the file
                exit(0); // exit from the program
    }
}

void swap(struct emp *x,struct emp *y)
{
    struct emp temp;
    temp = *x;
    *x = *y;
    *y = temp;
}


struct emp read_rec()
{
    struct emp e;
    char password[32] ;

    fflush(stdin);

    printf("\n Enter Employee Name                     :- ");
    scanf("%[^\n]s",e.name);

    printf("\n Enter Employee id                       :- ");
    scanf("%d",&e.emp_id);

    printf("\n Enter Employee Joining Date (dd/mm/yyyy):- ");
    scanf("%s",e.join_date);

    printf("\n Enter the Department of the Employee    :- ");
    scanf("%s",e.dept);

    printf("\n Enter Employee Salary                    :- ");
    scanf("%d",&e.sal);
    fflush(stdin);

    printf("\n Enter Password                           :- ");
    scanf("%s",e.password);
    while(1)
    {

        fflush(stdin);

        printf("\n Confirm Password                         :- ");
        scanf("%s",password);

        if(strcmp(e.password,password)==0)
            break;
        else
        {
            printf("\n Enter Password                    :- ");
            scanf("%s",e.password);
        }
    }

    fflush(stdin);

    printf("\n Enter Employee Address                   :- ");
    scanf("%s",e.pi.address);

    fflush(stdin);

    printf("\n Enter Employee Email id                  :- ");
    scanf("%s",e.pi.emailid);

    printf("\n Enter Employee Phone number              :- ");
    scanf("%s",e.pi.ph_no);

    printf("\n Enter Employee Emergency Phone number    :- ");
    scanf("%s",e.pi.emerph_no);
    return e;
}

void view_rec(struct emp e)
{
    printf("\n Employee name                      : %s ",e.name);
    printf("\n Employee ID                        : %d ",e.emp_id);
    printf("\n Employee Email ID                  : %s ",e.pi.emailid);
    printf("\n Employee Phone Number              : %s ",e.pi.ph_no);
    printf("\n Department                         : %s \n\n",e.dept);
}

void sort_sal_asc(FILE *fp,int n)
{
    struct emp e;
    struct emp f;
    int i , j;
    long int recsize=sizeof(e);

    for(i = 0 ; i<n-1 ; i++)
    {
        fread(&e,recsize,1,fp);
        fread(&f,recsize,1,fp);

        if(e.sal > f.sal)
        {
            swap(&e,&f);        //function call

            fseek(fp,-2*recsize,SEEK_CUR);
            fwrite(&e,recsize,1,fp);
            fwrite(&f,recsize,1,fp);
            rewind(fp);
            i=-1;
        }

        fseek(fp,-recsize,SEEK_CUR);

    }
}

void sort_sal_desc(FILE *fp,int n)
{
    struct emp e;
    struct emp f;
    int i , j;
    long int recsize=sizeof(e);

    for(i = 0 ; i<n-1 ; i++)
    {
        fread(&e,recsize,1,fp);
        fread(&f,recsize,1,fp);

        if(e.sal < f.sal)
        {
            swap(&e,&f);        //function call

            fseek(fp,-2*recsize,SEEK_CUR);
            fwrite(&e,recsize,1,fp);
            fwrite(&f,recsize,1,fp);
            rewind(fp);
            i=-1;
        }

        fseek(fp,-recsize,SEEK_CUR);

    }
}

void sort_name_asc(FILE *fp,int n)
{
    struct emp e;
    struct emp f;
    int i , j;
    long int recsize=sizeof(e);

    for(i = 0 ; i<n-1 ; i++)
    {
        fread(&e,recsize,1,fp);
        fread(&f,recsize,1,fp);

        if(strcmp(e.name, f.name) > 0)
        {
            swap(&e,&f);        //function call

            fseek(fp,-2*recsize,SEEK_CUR);
            fwrite(&e,recsize,1,fp);
            fwrite(&f,recsize,1,fp);
            rewind(fp);
            i=-1;
        }
        else
            fseek(fp,-recsize,SEEK_CUR);

    }
}

void sort_name_desc(FILE *fp,int n)
{
    struct emp e;
    struct emp f;
    int i , j;
    long int recsize=sizeof(e);

    for(i = 0 ; i<n-1 ; i++)
    {
        fread(&e,recsize,1,fp);
        fread(&f,recsize,1,fp);

        if(strcmp(e.name, f.name) < 0)
        {
            swap(&e,&f);        //function call

            fseek(fp,-2*recsize,SEEK_CUR);
            fwrite(&e,recsize,1,fp);
            fwrite(&f,recsize,1,fp);
            rewind(fp);
            i=-1;
        }

        fseek(fp,-recsize,SEEK_CUR);

    }
}

void sort_jd_asc(FILE *fp,int n)
{
    struct emp e;
    struct emp f;
    int i , j;
    int recsize=sizeof(e);
    double edatesum,fdatesum;
    double calc_datesum(struct emp);

    for(i = 0 ; i<n-1 ; i++)
    {
        fread(&e,recsize,1,fp);
        fread(&f,recsize,1,fp);

        edatesum=calc_datesum(e);
        fdatesum=calc_datesum(f);

        if(edatesum > fdatesum)
        {
            swap(&e,&f);        //function call

            fseek(fp,-2*recsize,SEEK_CUR);
            fwrite(&e,recsize,1,fp);
            fwrite(&f,recsize,1,fp);
            rewind(fp);
            i=-1;
        }

        fseek(fp,-recsize,SEEK_CUR);

    }
}

void sort_jd_desc(FILE *fp,int n)
{
    struct emp e;
    struct emp f;
    int i , j;
    int recsize=sizeof(e);
    double edatesum,fdatesum;
    double calc_datesum(struct emp);

    for(i = 0 ; i<n-1 ; i++)
    {
        fread(&e,recsize,1,fp);
        fread(&f,recsize,1,fp);

        edatesum=calc_datesum(e);
        fdatesum=calc_datesum(f);

        if(edatesum < fdatesum)
        {
            swap(&e,&f);        //function call

            fseek(fp,-2*recsize,SEEK_CUR);
            fwrite(&e,recsize,1,fp);
            fwrite(&f,recsize,1,fp);
            rewind(fp);
            i=-1;
        }

        fseek(fp,-recsize,SEEK_CUR);

    }
}


double calc_datesum(struct emp e)
{
    int year;
    int month;
    int day;
    double sum;

    year = 1000*(e.join_date[6]-48) + 100*(e.join_date[7]-48) + 10*(e.join_date[8]-48) + (e.join_date[9]-48) ;
    month = 10*(e.join_date[3]-48) + (e.join_date[4]-48) ;
    day  = 10*(e.join_date[0]-48) + (e.join_date[1]-48) ;
    sum = 1000000*year+10000*month+100*day;
    return(sum);
}

int checkentry(int id , char password[32] ,FILE *fp)
{
    struct emp e;
    int recsize=sizeof(e);

    while(fread(&e,recsize,1,fp))  // fetch all record from file
    {
        if((e.emp_id==id)&&strcmp(e.password,password)==0)  //if id and password matches
        {
            return 1;
        }
    }
    return 0;
}



int admin_pass()
{
    char pass[15]={0};                          // For taking i/p (password) from User for verification Purpose.
    char check[15]={0};                         // For fetching Original Password From the password File Store in the Disk.
    char ch;
    int j=0,i=0;

    printf("PLEASE! ENTER THE PASSWORD\n");
    printf("ONLY 3 CHANCES WILL BE GIVEN\n");

    for(i=0;i<=2;i++)                       // Loop Run 3 Times(Maximum).
    {
        j=0;
        printf("\n\n\nEnter the Password-> ");

        FILE *fptr=fopen("password.txt","rb");
        if(fptr == NULL)
        {
            FILE *fptr1=fopen("password.txt","wb");
            fprintf(fptr1,"%s","666");
            fclose(fptr1);

        }
        fclose(fptr);
        pass[0]=getch();                        // Main purpose is to Check, There is no Carriage Return (Enter) will be given by the user.
        while(pass[j]!='\r')                    // Checking Carriage Return.
        {
            if(pass[j]=='\b')                   // -->> Removes the Problem of removal of () from Screen while Typing the Password and enter backspace, then now with that the () all removed.
            {
                j--;
                printf("\b");                   // Backspace(For moving one Step Back).
                printf(" ");                    // Replace the * with Blank Space.
                printf("\b");                   // Then again, move One Step Back, & now we can move further (PROBLEM SOLVED).
                pass[j]=getch();                // Most Impotant Concept -->> To take cursor one step back and ready to take continious Input.
            }
            else
            {
                printf("*");                    // Shows like that we Enter Password on the Screen in the HIDDEN format i.e () Format.here * is used
                j++;
                pass[j]=getch();                // Storing Pasword from User Side For Comparision Purpose.
            }
        }
        pass[j]='\0';                           // Adding NULL at the Last helps to Check Termination point of the CHARACTER ARRAY i.e. (String).
        FILE *fp;                               // file pointer to the password file.

        fp = fopen("password.txt","rb");             // Opening in the Read Mode.
        if(fp==NULL)                            // Checking the presence of password File.
        {
            printf(" [FILE MISSING]");
            getch();
            return 1;
        }
        else
        {
            j=0;
            while(1)
            {
                ch=fgetc(fp);                   // Taking i/p Character by Character.
                if(ch==EOF)
                {
                    check[j]='\0';              // Adding NULL at the Last helps to Check Termination point of the CHARACTER ARRAY i.e. (String).
                    break;
                }
                check[j]=ch-5;                  // Decrypting Technique.
                j++;
            }
        }

        if(strcmp(pass,check)==0)           // Compare the User Password with Original Password.
        {
            printf("\n\t\t\tACCESS GRANTED \n");
            return 0;
        }
        else
        {
            printf("\n\t\t\tWRONG PASSWORD \n");
        }
        fclose(fp);                             // Close the password file.
    }
    printf("YOU ARE NOT ALLOWED TO ENTER");
    getch();
    return 1;
}




void edit_admin()
{
    system("cls");                                                 // Clear the Screen.

    char pass[15]={0}, verify[15]={0};
    char ch;
    int match,i=0,choice;

    printf("\n\n");
    FILE *fp;                                                       // File Pointer to password file
    fp=fopen("password.txt","rb");                                      // Read Binary Mode
    if(fp==NULL)
    {
        fp=fopen("password.txt","wb");
        if(fp==NULL)                                                // Write Binary Mode
        {
            printf("SYSTEM ISSUE -_-");
            getch();
            return ;
        }
        fclose(fp);
        printf("\nYOUR PASSWORD IS 'ENTER'\n PRESS ENTER TO CHANGE PASSWORD\n\n");
        getch();
    }
    fclose(fp);
    match=admin_pass();
    if(match==1)
    {
        return;
    }
    do
    {
        if(match==0)
        {
            printf("\nEnter the NEW password -> ");
            fflush(stdin);
            pass[0]=getch();
            while(pass[i]!='\r')
            {
                if(pass[i]=='\b')
                {
                    i--;
                    printf("\b");
                    printf(" ");
                    printf("\b");
                    pass[i]=getch();
                }
                else
                {
                    printf("*");
                    i++;
                    pass[i]=getch();
                }
            }
            pass[i]='\0';
            i=0;
            printf("\nConfirm Password -> ");
            verify[0]=getch();
            while(verify[i]!='\r')
            {
                if(verify[i]=='\b')
                {
                    i--;
                    printf("\b");
                    printf(" ");
                    printf("\b");
                    verify[i]=getch();
                }
                else
                {
                    printf("*");
                    i++;
                    verify[i]=getch();
                }
            }
            verify[i]='\0';
            if(strcmp(pass,verify)==0)
            {
                fp=fopen("password.txt","wb");
                if(fp==NULL)
                {
                    printf("SYSTEM ERROR -_-");
                    getch();
                    return;
                }
                i=0;
                while(pass[i]!='\0')
                {
                    ch=pass[i];
                    putc(ch+5,fp);
                    i++;
                }
                putc(EOF,fp);
                fclose(fp);
            }
            else
            {
                printf("\nWRONG PASSWORD");
                choice=1;
            }
        }
    }
    while(choice==1);
    printf("\n\n\t\tPassword Changed");
    getch();
}
